site_name: AWS Foundational Concepts
theme:
  name: material
  icon:
    logo: fontawesome/brands/aws
  font:
    text: Roboto

nav:
  - Cloud Computing:
      - Introduction: cloud-computing-basics.md
      - AWS CAF: aws-caf.md
      - Cloud Architecture: cloud-architecture.md
      - AWS WAF: waf.md
      - AWS Trusted Advisor: aws-ta.md
      - Best Practices: best-practices.md

  - Global Infrastructure:
      - Region: region.md
      - Availability Zone: availability-zone.md
      - Data Center: data-center.md
      - Local Zone: local-zones.md
      - Points of Presence: pop.md

  - Cloud Economics & Billing:
      - Pricing Model: pricing-model.md
      - AWS Organization: organizations.md
      - AWS Billing: billing.md
      - Technical Support: support.md

  - Cloud Security:
      - IAM: iam.md
      - AWS CloudTrail: cloud-trail.md
      - Access Control: access-control.md
      - AWS KMS: aws-kms.md
      - AWS Cognito: cognito.md
      - AWS Shield: shield.md
      - Data Encryption: encryption.md
      - AWS Config: config.md
      - AWS Artifact: artifact.md

  - Network Environment:
      - Networking Basics: networking-basics.md
      - Amazon VPC: vpc.md
      - VPC Networking: vpc-networking.md
      - VPC Security: vpc-security.md
      - Route 53: route-53.md
      - CloudFront: cloudfront.md

  - Compute:
      - EC2 Introduction: compute-services.md
      - EC2 Pricing Model: ec2-pricing.md
      - EC2 Cost Optimization: ec2-cost-optimization.md
      - Container Services: container-services.md
      - Amazon ECS: ecs.md
      - Amazon EKS: eks.md
      - Amazon ECR: ecr.md
      - AWS Lambda: lambda.md
      - AWS Elastic Beanstalk: beanstalk.md
      - Placement Group: placement-group.md

  - Storage:
      - AWS EBS: ebs.md
      - AWS S3: s3.md
      - AWS EFS: efs.md

  - Database:
      - Amazon RDS: rds.md
      - Amazon DynamoDB: dynamodb.md

  - Scaling and Monitoring:
      - Scaling Compute Capacity: ec2-auto-scaling.md
      - Scaling Database Resource: scaling-db.md
      - Highly Available Environment: load-balancing.md
      - Monitoring: cloudwatch.md

  - Caching Content:
      - Edge Caching: edge-caching.md
      - Elastic Cache: elastic-cache.md

  - Application Architecture:
      - Decoupled Architecture: decoupled-architecture.md
      - Microservice Architecture: index.md
      - Serverless Architecture: index.md

  - Disaster Planning:
      - Basics: index.md
