site_name: AWS Foundational Concepts
theme:
  name: material
  icon:
    logo: fontawesome/brands/aws
  font:
    text: Roboto

nav:
  - Cloud Computing:
      - Introduction: cloud-computing-basics.md
      - AWS CAF: aws-caf.md
      - Cloud Architecture: cloud-architecture.md
      - AWS WAF: waf.md
      - Best Practices: best-practices.md

  - Global Infrastructure:
      - Region: region.md
      - Availability Zone: availability-zone.md
      - Data Center: data-center.md
      - Local Zone: local-zones.md
      - Points of Presence: pop.md

  - Cloud Economics & Billing:
      - Pricing Model: pricing-model.md
      - AWS Organization: organizations.md
      - AWS Billing: billing.md
      - Technical Support: support.md

  - Cloud Security:
      - IAM: iam.md
      - AWS CloudTrail: cloud-trail.md
      - Access Control: access-control.md
      - AWS KMS: aws-kms.md
      - AWS Cognito: cognito.md
      - AWS Shield: shield.md
      - Data Encryption: encryption.md
      - AWS Config: config.md
      - AWS Artifact: artifact.md

  - Network Environement:
      - Basics: index.md

  - Compute:
      - Basics: index.md

  - Storage:
      - Basics: index.md

  - Database:
      - Basics: index.md

  - Cloud Architecture:
      - Basics: index.md

  - Caching Content:
      - Basics: index.md

  - Decoupled Architecture:
      - Basics: index.md

  - Microservices Architecture:
      - Basics: index.md

  - Serverless Architecture:
      - Basics: index.md

  - Disaster Planning:
      - Basics: index.md
